### ISSUE TITLE
Week 2 Day 1 Daily challenge

### ISSUE THREAD

**Issue by Nomekuma** [L15ami/DI_Bootcamp_Javascript#1]
https://github.com/L15ami/DI_Bootcamp_Javascript/blob/912f03174e051bf7c6cc935c5c13099399823979/Week%202/Day_1/Daily_challenge/Daily_challenge.js#L3
- In the codebase, there is a line of code that uses fruits.splice(0, 1) to remove the first element from an array. While this approach works, it can be simplified and made more concise by using fruits.shift().

***Overall || Pass***
Good job 🥳

**Comment by L15ami** [comment]
I'll try use it next time
